name: docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies 1
      run: pip install -r requirements.txt
    - name: Install dependencies 2
      uses: opt-nc/setup-duckdb-action@v1.0.7
      with:
        version: v1.0.0
    - name: Run dbt
      run: |
        dbt build
    - name: Deploy dbt docs
      run: |
        dbt docs generate
        mkdir docs
        cp dbt/target/manifest.json docs/manifest.json
        cp dbt/target/catalog.json docs/catalog.json
        cp dbt/target/index.html docs/index.html
        cp -r dbt/target/ target/
        ghp-import -n -p -f docs/
      env:
        DBT_PROJECT_DIR: ./dbt
        DBT_PROFILES_DIR: ./dbt_profiles

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/
