name: docs
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'data/full.parquet'

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run duckdb data extract
      run: python ./duckdb-extract/duckdb-extract.py
    - name: Deploy dbt docs
      run: |
        dbt docs generate
        mkdir docs
        cp dbt/target/manifest.json docs/manifest.json
        cp dbt/target/catalog.json docs/catalog.json
        cp dbt/target/index.html docs/index.html
        cp -r dbt/target/ target/
        ghp-import -n -p -f docs/
      env:
        DBT_PROJECT_DIR: ./dbt
        DBT_PROFILES_DIR: ./dbt_profiles
    - name: Run dbt
      run: |
        dbt run
      env:
        DBT_PROJECT_DIR: ./dbt
        DBT_PROFILES_DIR: ./dbt_profiles

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git reset -- ./docs ./data
        git commit -m "Automated commit by GitHub Actions"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
